import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { ConditionalFloatingChat } from "@/components/shared/conditional-floating-chat";
import Bubbles from "@/components/shared/bg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Bubbles /> */}
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-1 flex-col">
            <SidebarTrigger className="m-4" />
            {children}
          </main>
        </SidebarProvider>
        <ConditionalFloatingChat />
        <Toaster />
      </body>
    </html>
  );
}
